version: '3.5'

services:
  piauki:
    build: piauki
  susing:
    image: i3thuan5/taigi_susing
    command: gunicorn -w 2 -b 0.0.0.0:5000 --log-level debug 標詞性:app
    expose:
        - 5000
    restart: always
  kuhuat:
    image: stanford_hua5gi2_nlp_flask_server
    depends_on:
      - stanford
    expose:
      - "5000"
    environment:
      VIRTUAL_HOST: "xn--lhrz38b.xn--v0qr21b.xn--kpry57d"
      VIRTUAL_PORT: 5000
    restart: always
  stanford:
    image: a8568730/stanford_hua5gi2_nlp
    restart: always
  huanik:
    image: i3thuan5/su5-sing3_tai5-hua5
    expose:
      - "8080"
    restart: always
    
