FROM i3thuan5/hok8-bu7
MAINTAINER Sing-hong

RUN pip install nltk
RUN pip install --upgrade https://github.com/i3thuan5/tai5-uan5_gian5-gi2_kang1-ku7/archive/Bootsoohua-piantiau.zip

COPY kiatko.py sngpiauki.py ./

CMD python kiatko.py 逐-家｜tak8-ke1 做-伙｜tso3-hue2 來｜lai5 𨑨-迌｜tshit4-tho5 ！｜!

